### PR TITLE
Make feeds auto-discoverable by Feed Readers

### PR DESCRIPTION
**Pull request by GreenLunar**
See https://www.rssboard.org/rss-autodiscovery

### CODE REVIEW

**Comment by pluja** [comment]
Looks good to me, maybe you could add those title changes before I merge, if you think that would be good?

**Comment by GreenLunar** [comment]
There is another problem with this commit.

If blog is located at https://blogo.site/blog the links above will be redirected to https://blogo.site/rss instead of https://blogo.site/blog/rss.

Solutions:
1) an absolute URL is written there (recommended).
2) Add `<base href="https://blogo.site/blog/">` is added.

I prefer solution # 1.

**Comment by GreenLunar** [comment]
> Looks good to me, maybe you could add those title changes before I merge, if you think that would be good?

I'm not sure I understand the syntax nor do I have an environment to check this.

Please feel free to make an edit or even make a new PR.

The appearance of my credentials is not crucial to me.

**Comment by GreenLunar** [comment]
Done.

But I still didn't solve the URL issue.

Could you do it please?

I will make a test whenever you ask.

**Comment by pluja** [comment]
Since blogo has access to the `BLOGO_URL` environment variable, that should be set to the actual blogo URL, we can use that. I made a commit, check it out and if you thinks that looks good, I'll merge!

**Comment by GreenLunar** [comment]
Please pardonme  for the late respond.

It looks good to me.

Please apply this to https://blogo.site/ as I'd like to test it.

**Pull request merged**
